name: 'Validate JSON Schemas'
description: 'Find json files and validate them agains $schema'
branding:
    icon: 'check-circle'
    color: 'blue'
inputs:
    files:
        description: 'Files to validate'
        required: true
    schema:
        description: 'Schema location'
        required: false
    schema-version:
        description: 'Choose schema version'
        default: draft-04
        required: false
    print-valid-files:
        description: 'Print valid file names to console'
        default: false
        required: false
    allow-matching-properties:
        description: 'Pass true to allow overlap between "properties" and "patternProperties"'
        default: false
        required: false
runs:
    using: 'node12'
    main: 'dist/index.js'
