name: Static Analysis (Linting...)

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    check:
        name: JavaScript and Styles
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set Node.js 12.x
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: 12.x

            - name: Npm install
              run: npm ci

            - name: Lint JavaScript
              run: npm run lint

            - name: Type checking
              run: npm run tsc
