name: Static Analysis (Linting...)

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    check:
        name: JavaScript and Styles
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set Node.js 16.x
              uses: actions/setup-node@v3.6.0
              with:
                  node-version: 16.x

            - name: Npm install
              run: npm ci

            - name: Format Code
              run: npm run format

            - name: Compare the expected and actual content after formatting files
              run: |
                  if [ "$(git diff | wc -l)" -gt "0" ]; then
                    echo "Detected changes after formatting files. Please format code with Prettier. See changed files below:"
                    git diff --name-only
                    exit 1
                  fi

            - name: Lint JavaScript
              run: npm run lint

            - name: Type checking
              run: npm run tsc
